version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: iscan-db
    restart: always
    environment:
      POSTGRES_USER: iscan
      POSTGRES_PASSWORD: iscan_pass
      POSTGRES_DB: iscan_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: iscan-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: iscan-api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    container_name: iscan-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  pgdata:
