const STATES = Object.freeze({
  CREATED: 'created',
  VALIDATING: 'validating',
  FRAUD_CHECK: 'fraud_check',
  RESERVED: 'reserved',
  PROCESSING: 'processing',
  ONRAMP_PENDING: 'onramp_pending',  // NEW: waiting for GCash + crypto
  ONRAMP_COMPLETED: 'onramp_completed', // NEW: crypto received
  SETTLED: 'settled',
  FAILED: 'failed',
  REVERSED: 'reversed'
});

const TRANSITIONS = {
  [STATES.CREATED]: [ STATES.VALIDATING, STATES.FAILED ],
  [STATES.VALIDATING]: [ STATES.FRAUD_CHECK, STATES.FAILED ],
  [STATES.FRAUD_CHECK]: [ STATES.RESERVED, STATES.FAILED ],
  [STATES.RESERVED]: [ STATES.PROCESSING, STATES.ONRAMP_PENDING, STATES.FAILED ], // Added ONRAMP_PENDING
  [STATES.PROCESSING]: [ STATES.SETTLED, STATES.FAILED ],
  [STATES.ONRAMP_PENDING]: [ STATES.ONRAMP_COMPLETED, STATES.FAILED ], // NEW
  [STATES.ONRAMP_COMPLETED]: [ STATES.SETTLED ], // NEW
  [STATES.SETTLED]: [ STATES.REVERSED ],
  [STATES.REVERSED]: [],
  [STATES.FAILED]: []
};
